# Generated by Django 6.0.3 on 2026-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_lbp_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_recommended_decision',
            field=models.CharField(blank=True, choices=[('no_action', 'No Action Required'), ('further_review', 'Further Review Recommended'), ('escalate', 'Escalate to Investigator'), ('refer_for_prosecution', 'Refer for Prosecution')], max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_verdict',
            field=models.CharField(blank=True, choices=[('authentic', 'Authentic'), ('likely_manipulated', 'Likely Manipulated'), ('fake', 'Fake'), ('inconclusive', 'Inconclusive')], max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='victim_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
