# Generated by Django 6.0.3 on 2026-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_portal', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='victim_name',
            new_name='victim_first_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='victim_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='victim_middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
