# Generated by Django 6.0.3 on 2026-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_portal', '0004_rename_victim_name_complaint_victim_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='perpetrator_name',
            new_name='perpetrator_first_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='perpetrator_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='perpetrator_middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
